# Generated by Django 3.1.5 on 2021-01-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquire_forms', '0002_auto_20210130_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
